algoritmo "AULA 19"
// CADASTRO DE LIVROS

var
 livro: caractere
 cont, qtdd: inteiro

inicio

      escreval ("Quantos livros deseja cadastrar?")
      leia (qtdd)

      cont <- 0
      enquanto (cont < qtdd) faca

               escreval ("ID: ",cont)
               
               escreval ("Livro")
               leia (livro)

               escreval ()

               cont <- cont + 1

      fimenquanto

fimalgoritmo

